/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'canvas-warm': '#FBF9F6',
        'canvas-alt': '#F5F3F0',
        'canvas-sheet': '#EFECE6',
        'editorial-ink': '#1B1B1B',
        'editorial-red': '#D72626',
        'editorial-red-deep': '#B91C1C',
        'editorial-gray': '#6B6B6B',
        'grid-border': '#E5E0D8',
        'surface': '#FBF9F6',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F3F0',
        'surface-container': '#EFECE6',
        'primary-container': '#D72626',
        'pure-black': '#000000',
        'pure-white': '#FFFFFF',
        'secondary': '#6B6B6B',
        'on-surface-variant': '#4A4A4A',
        'primary': '#1B1B1B',
        'grid-line': '#E5E0D8',
      },
      fontFamily: {
        display: ['Anton', 'Impact', 'sans-serif'],
        serif: ['Anton', 'Impact', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
        sans: ['Inter', 'sans-serif'],
        'headline-lg': ['Anton', 'Impact', 'sans-serif'],
        'headline-md': ['Anton', 'Impact', 'sans-serif'],
        'label-code': ['"Space Mono"', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      screens: {
        'xs': '400px',
      },
      spacing: {
        'unit-2xs': '0.25rem',
        'unit-xs': '0.5rem',
        'unit-sm': '0.75rem',
        'unit-md': '1rem',
        'unit-lg': '1.5rem',
        'unit-xl': '2.5rem',
        'unit-2xl': '4rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '2rem',
        'margin-mobile': '1.25rem',
        'margin-desktop': '3rem',
      },
      maxWidth: {
        container: '1780px',
      },
    },
  },
  plugins: [],
};
